"""V8 (MUA / Alchemy 5.0) meta tables. AUTO-GENERATED - do not edit.

Generated by tools/gen_v8_meta.py from a native MUA v8 actor
(Games/Marvel Ultimate Alliance/actors/0201.igb). Layouts are
verbatim extractions the MUA engine already loads.
"""

# (name, major, minor)
V8_META_FIELDS = [
    ('igUnsignedCharMetaField', 1, 0),
    ('igObjectRefMetaField', 1, 0),
    ('igCharMetaField', 1, 0),
    ('igStructMetaField', 1, 0),
    ('igIntMetaField', 1, 0),
    ('igCharArrayMetaField', 1, 0),
    ('igIntArrayMetaField', 1, 0),
    ('igUnsignedIntMetaField', 1, 0),
    ('igRawRefMetaField', 1, 0),
    ('igShortMetaField', 1, 0),
    ('igStringMetaField', 1, 0),
    ('igBoolMetaField', 1, 0),
    ('igMemoryRefMetaField', 1, 0),
    ('igMemoryDescriptorMetaField', 1, 0),
    ('igFloatMetaField', 1, 0),
    ('igLongMetaField', 1, 0),
    ('igEnumMetaField', 1, 0),
    ('igIGBMetaInfoStructMetaField', 1, 0),
    ('igUnsignedLongMetaField', 1, 0),
    ('igObjectRefArrayMetaField', 1, 0),
    ('igStatisticDataMetaField', 1, 0),
    ('igUnsignedCharArrayMetaField', 1, 0),
    ('igDoubleMetaField', 1, 0),
    ('igUnsignedShortMetaField', 1, 0),
    ('igDependencyMetaField', 1, 0),
    ('igVirtualCFuncMetaField', 1, 0),
    ('igUnsignedShortArrayMetaField', 1, 0),
    ('igUnsignedLongArrayMetaField', 1, 0),
    ('igUnsignedIntArrayMetaField', 1, 0),
    ('igStringArrayMetaField', 1, 0),
    ('igShortArrayMetaField', 1, 0),
    ('igRawRefArrayMetaField', 1, 0),
    ('igMemoryRefArrayMetaField', 1, 0),
    ('igLongArrayMetaField', 1, 0),
    ('igFloatArrayMetaField', 1, 0),
    ('igEnumArrayMetaField', 1, 0),
    ('igDoubleArrayMetaField', 1, 0),
    ('igBoolArrayMetaField', 1, 0),
    ('igVec3fMetaField', 1, 0),
    ('igVec2fMetaField', 1, 0),
    ('igVec4fMetaField', 1, 0),
    ('igVec3ucMetaField', 1, 0),
    ('igVec4ucMetaField', 1, 0),
    ('igVec3fAlignedMetaField', 1, 0),
    ('igVec4fAlignedMetaField', 1, 0),
    ('igMatrix44fMetaField', 1, 0),
    ('igVec4fArrayMetaField', 1, 0),
    ('igTrackedElementMetaField', 1, 0),
    ('igVec4iMetaField', 1, 0),
    ('igItemDataBaseField', 1, 0),
    ('igInterfaceDeclarationField', 1, 0),
    ('igCharMetricsMetaField', 1, 0),
]

# (name, major, minor, parent_name, slot_count, [(field_short, slot, size)])
V8_META_OBJECTS = [
    # [0]
    ('igObject', 1, 0, None, 2,
     []),
    # [1]
    ('igNamedObject', 1, 0, 'igObject', 3,
     [('String', 2, 4)]),
    # [2]
    ('igDirEntry', 1, 0, 'igNamedObject', 7,
     [('String', 2, 4)]),
    # [3]
    ('igObjectDirEntry', 1, 0, 'igDirEntry', 13,
     [('String', 2, 4), ('Int', 11, 4), ('Int', 12, 4)]),
    # [4]
    ('igMemoryDirEntry', 1, 0, 'igDirEntry', 14,
     [('String', 2, 4), ('Int', 7, 4), ('Int', 10, 4), ('Bool', 11, 1), ('Int', 12, 4), ('Int', 13, 4)]),
    # [5]
    ('igExternalDirEntry', 1, 0, 'igDirEntry', 11,
     [('String', 2, 4), ('String', 7, 4), ('String', 8, 4), ('Int', 9, 4)]),
    # [6]
    ('igExternalImageEntry', 1, 0, 'igExternalDirEntry', 11,
     [('String', 2, 4), ('String', 7, 4), ('String', 8, 4), ('Int', 9, 4)]),
    # [7]
    ('igExternalIndexedEntry', 1, 0, 'igDirEntry', 13,
     [('String', 2, 4), ('Int', 7, 4), ('Int', 8, 4), ('Int', 10, 4), ('Int', 12, 4)]),
    # [8]
    ('igExternalInfoEntry', 1, 0, 'igDirEntry', 10,
     [('String', 2, 4), ('String', 7, 4), ('Int', 8, 4), ('String', 9, 4)]),
    # [9]
    ('igAnimationCombinerBoneInfo', 1, 0, 'igObject', 11,
     [('ObjectRef', 2, 4), ('ObjectRef', 3, 4), ('Vec4f', 4, 16), ('Vec3f', 5, 12), ('Int', 6, 4), ('UnsignedChar', 7, 1), ('Int', 9, 4)]),
    # [10]
    ('igDataList', 1, 0, 'igObject', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [11]
    ('igObjectList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [12]
    ('igInfoList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [13]
    ('igTextureList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [14]
    ('igGraphPathList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [15]
    ('igNodeList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [16]
    ('igPropertyValue', 1, 0, 'igObject', 2,
     []),
    # [17]
    ('igStringValue', 1, 0, 'igPropertyValue', 3,
     [('String', 2, 4)]),
    # [18]
    ('igPropertyKey', 1, 0, 'igObject', 2,
     []),
    # [19]
    ('igStringKey', 1, 0, 'igPropertyKey', 3,
     [('String', 2, 4)]),
    # [20]
    ('igPropertyList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [21]
    ('igAnimationState', 1, 0, 'igObject', 28,
     [('ObjectRef', 2, 4), ('Enum', 3, 4), ('Enum', 4, 4), ('Enum', 5, 4), ('ObjectRef', 6, 4), ('Bool', 7, 1), ('Float', 8, 4), ('Long', 9, 8), ('Long', 10, 8), ('Float', 11, 4), ('Long', 12, 8), ('Long', 13, 8), ('Float', 14, 4), ('Float', 15, 4), ('Long', 16, 8), ('Long', 17, 8), ('ObjectRef', 20, 4), ('Bool', 21, 1), ('Bool', 22, 1), ('Bool', 23, 1), ('Long', 24, 8), ('Long', 25, 8), ('Long', 26, 8)]),
    # [22]
    ('igNode', 1, 0, 'igNamedObject', 7,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4)]),
    # [23]
    ('igGroup', 1, 0, 'igNode', 8,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4)]),
    # [24]
    ('igAttrSet', 1, 0, 'igGroup', 10,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1)]),
    # [25]
    ('igAttr', 1, 0, 'igObject', 4,
     [('Short', 2, 2)]),
    # [26]
    ('igVisualAttribute', 1, 0, 'igAttr', 4,
     [('Short', 2, 2)]),
    # [27]
    ('igCullFaceAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 2, 2), ('Bool', 4, 1), ('Enum', 5, 4)]),
    # [28]
    ('igImageMipMapList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [29]
    ('igAttrList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [30]
    ('igVolume', 1, 0, 'igObject', 2,
     []),
    # [31]
    ('igAABox', 1, 0, 'igVolume', 4,
     [('Vec3f', 2, 12), ('Vec3f', 3, 12)]),
    # [32]
    ('igTextureAttr', 1, 0, 'igVisualAttribute', 19,
     [('Short', 2, 2), ('UnsignedInt', 4, 4), ('Enum', 5, 4), ('Enum', 6, 4), ('Enum', 7, 4), ('Enum', 8, 4), ('Enum', 10, 4), ('Enum', 11, 4), ('ObjectRef', 12, 4), ('Bool', 13, 1), ('ObjectRef', 14, 4), ('Int', 15, 4), ('ObjectRef', 16, 4)]),
    # [33]
    ('igVertexBlendStateAttr', 1, 0, 'igVisualAttribute', 5,
     [('Short', 2, 2), ('Bool', 4, 1)]),
    # [34]
    ('igColorAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 2, 2), ('Vec4f', 4, 16)]),
    # [35]
    ('igTextureStateAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 2, 2), ('Bool', 4, 1), ('Int', 5, 4)]),
    # [36]
    ('igMaterialAttr', 1, 0, 'igVisualAttribute', 10,
     [('Short', 2, 2), ('Float', 4, 4), ('Vec4f', 5, 16), ('Vec4f', 6, 16), ('Vec4f', 7, 16), ('Vec4f', 8, 16), ('UnsignedInt', 9, 4)]),
    # [37]
    ('igTextureBindAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 2, 2), ('ObjectRef', 4, 4), ('Int', 5, 4)]),
    # [38]
    ('igGlobalColorStateAttr', 1, 0, 'igVisualAttribute', 5,
     [('Short', 2, 2), ('Bool', 4, 1)]),
    # [39]
    ('igImage', 1, 0, 'igObject', 23,
     [('UnsignedInt', 2, 4), ('UnsignedInt', 3, 4), ('UnsignedInt', 4, 4), ('Enum', 5, 4), ('Enum', 6, 4), ('UnsignedInt', 7, 4), ('UnsignedInt', 8, 4), ('UnsignedInt', 9, 4), ('UnsignedInt', 10, 4), ('Enum', 11, 4), ('Int', 12, 4), ('MemoryRef', 13, 4), ('MemoryRef', 14, 4), ('Bool', 15, 1), ('UnsignedInt', 16, 4), ('ObjectRef', 17, 4), ('UnsignedInt', 18, 4), ('Int', 19, 4), ('Bool', 20, 1), ('UnsignedInt', 21, 4), ('String', 22, 4)]),
    # [40]
    ('igDrawableAttr', 1, 0, 'igVisualAttribute', 4,
     [('Short', 2, 2)]),
    # [41]
    ('igGeometryAttr2', 1, 0, 'igDrawableAttr', 13,
     [('Short', 2, 2), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('Enum', 7, 4), ('UnsignedInt', 8, 4), ('UnsignedInt', 9, 4), ('UnsignedInt', 10, 4), ('Bool', 11, 1)]),
    # [42]
    ('igGeometry', 1, 0, 'igAttrSet', 10,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1)]),
    # [43]
    ('igSkeletonBoneInfo', 1, 0, 'igNamedObject', 6,
     [('String', 2, 4), ('Int', 3, 4), ('Int', 4, 4), ('Int', 5, 4)]),
    # [44]
    ('igAnimationTrack', 1, 0, 'igNamedObject', 6,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Vec4f', 4, 16), ('Vec3f', 5, 12)]),
    # [45]
    ('igAnimation', 1, 0, 'igNamedObject', 11,
     [('String', 2, 4), ('Int', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('Long', 7, 8), ('Long', 8, 8), ('Long', 9, 8), ('ObjectRef', 10, 4)]),
    # [46]
    ('igIntList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [47]
    ('igAnimationCombinerBoneInfoList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [48]
    ('igProperty', 1, 0, 'igObject', 4,
     [('ObjectRef', 2, 4), ('ObjectRef', 3, 4)]),
    # [49]
    ('igInfo', 1, 0, 'igNamedObject', 5,
     [('String', 2, 4), ('Bool', 4, 1)]),
    # [50]
    ('igSceneInfo', 1, 0, 'igInfo', 12,
     [('String', 2, 4), ('Bool', 4, 1), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('Long', 8, 8), ('Long', 9, 8), ('Vec3f', 10, 12), ('ObjectRef', 11, 4)]),
    # [51]
    ('igUserInfo', 1, 0, 'igGroup', 9,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4)]),
    # [52]
    ('igHashedUserInfo', 1, 0, 'igUserInfo', 10,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4)]),
    # [53]
    ('igSegment', 1, 0, 'igGroup', 8,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4)]),
    # [54]
    ('igVertexData', 1, 0, 'igNamedObject', 14,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Enum', 4, 4), ('UnsignedInt', 5, 4), ('UnsignedInt', 6, 4), ('Int', 7, 4), ('UnsignedInt', 8, 4), ('Vec4f', 9, 16), ('Vec4f', 10, 16), ('Bool', 11, 1), ('Int', 12, 4)]),
    # [55]
    ('igVec2fList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [56]
    ('igFloatList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [57]
    ('igVertexArray2', 1, 0, 'igNamedObject', 6,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('ObjectRef', 4, 4)]),
    # [58]
    ('igVec3fList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [59]
    ('igVertexStream', 1, 0, 'igNamedObject', 10,
     [('String', 2, 4), ('ObjectRef', 5, 4), ('Enum', 6, 4), ('Enum', 7, 4), ('Enum', 8, 4), ('Bool', 9, 1)]),
    # [60]
    ('igUnsignedCharList', 1, 0, 'igDataList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [61]
    ('igAnimationBindingList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [62]
    ('igBlendMatrixSelect', 1, 0, 'igAttrSet', 13,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1), ('ObjectRef', 10, 4), ('Matrix44f', 11, 64), ('Matrix44f', 12, 64)]),
    # [63]
    ('igAnimationBinding', 1, 0, 'igObject', 7,
     [('ObjectRef', 2, 4), ('MemoryRef', 3, 4), ('Int', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4)]),
    # [64]
    ('igActor', 1, 0, 'igGroup', 21,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('Int', 5, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('MemoryRef', 9, 4), ('MemoryRef', 10, 4), ('ObjectRef', 11, 4), ('ObjectRef', 12, 4), ('ObjectRef', 13, 4), ('Matrix44f', 14, 64)]),
    # [65]
    ('igSkin', 1, 0, 'igNamedObject', 5,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('ObjectRef', 4, 4)]),
    # [66]
    ('igAppearance', 1, 0, 'igNamedObject', 8,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4)]),
    # [67]
    ('igAnimationModifierList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [68]
    ('igSkeletonBoneInfoList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [69]
    ('igAnimationCombinerBoneInfoListList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [70]
    ('igAnimationSystem', 1, 0, 'igNamedObject', 4,
     [('String', 2, 4), ('ObjectRef', 3, 4)]),
    # [71]
    ('igAnimationCombiner', 1, 0, 'igAnimationSystem', 18,
     [('String', 2, 4), ('ObjectRef', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('MemoryRef', 7, 4), ('MemoryRef', 8, 4), ('Long', 9, 8), ('Bool', 10, 1), ('MemoryRef', 12, 4), ('MemoryRef', 13, 4), ('Long', 14, 8), ('Long', 15, 8), ('Long', 16, 8), ('Long', 17, 8)]),
    # [72]
    ('igAnimationStateList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [73]
    ('igSkeleton', 1, 0, 'igNamedObject', 7,
     [('String', 2, 4), ('MemoryRef', 3, 4), ('ObjectRef', 4, 4), ('MemoryRef', 5, 4), ('Int', 6, 4)]),
    # [74]
    ('igAnimationTrackList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [75]
    ('igModelViewMatrixBoneSelectList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [76]
    ('igActorInfo', 1, 0, 'igInfo', 10,
     [('String', 2, 4), ('Bool', 4, 1), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('ObjectRef', 9, 4)]),
    # [77]
    ('igAnimationCombinerList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [78]
    ('igActorList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [79]
    ('igStringObjList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [80]
    ('igAppearanceList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [81]
    ('igSkinList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [82]
    ('igAnimationDatabase', 1, 0, 'igInfo', 10,
     [('String', 2, 4), ('Bool', 4, 1), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('ObjectRef', 9, 4)]),
    # [83]
    ('igSkeletonList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [84]
    ('igAnimationList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
    # [85]
    ('igAnimationTransitionDefinitionList', 1, 0, 'igObjectList', 5,
     [('Int', 2, 4), ('Int', 3, 4), ('MemoryRef', 4, 4)]),
]

N_META_OBJECTS = 86
N_META_FIELDS = 52

V8_ALIGNMENT = bytes.fromhex('5b0000000100000005000000090000000a000000100000000d0000000b000000436c75744461746100496d616765446174610056657274657841727261794461746100474356657274657844617461005665727465784461746100')

# Memory pool name table, VERBATIM from the native v8 donor.
# The MUA engine keys allocation on these indices; our previous
# hand-typed table was shifted (missing System2/ASP/PPFX/Effect)
# so every pool handle we wrote pointed at the wrong pool.
V8_MEMORY_POOL_NAMES = [
    'Bootstrap',
    'System',
    'System2',
    'Static',
    'MetaData',
    'String',
    'NonTracked',
    'Default',
    'Fast',
    'AGP',
    'VRAM',
    'Auxiliary',
    'LongTerm',
    'MediumTerm',
    'ShortTerm',
    'Application',
    'VisualContext',
    'ASP',
    'PPFX',
    'Effect',
    'Statistics',
    'Level',
    'World',
    'Actor',
    'AnimationData',
    'Geometry',
    'Vertex',
    'Image',
    'ImageObject',
    'Attribute',
    'Node',
    'Physics',
    'AI',
    'Audio',
    'Video',
    'Temporary',
    'DMA',
    'Shader',
    'RenderList',
    'Texture',
    'Clut',
    'DriverData',
    'Handles',
    'List',
    'User0',
    'User1',
    'User2',
    'User3',
    'User4',
    'User5',
    'User6',
    'User7',
    'User8',
    'User9',
    'User10',
    'User11',
    'User12',
    'User13',
    'User14',
    'User15',
    'User16',
    'User17',
    'User18',
    'User19',
    'User20',
    'User21',
    'User22',
    'User23',
    'User24',
    'User25',
    'User26',
    'User27',
    'User28',
    'User29',
    'User30',
    'User31',
]
