"""V4 meta tables for Max-style skin export. AUTO-GENERATED - do not edit.

Generated by tools/gen_v4_meta.py from donor files the XML2 engine
demonstrably loads:
  [0..59]  0103.igb (community skin, loads + plays all anims)
  [60..73] 210xxcableMUA2.igb (Max export, grounds resized skeleton)
Layouts are verbatim extractions — no hand translation.
"""

# (name, major, minor) — 0103.igb order
V4_META_FIELDS = [
    ('igBoolMetaField', 1, 0),
    ('igCharMetaField', 1, 0),
    ('igShortMetaField', 1, 0),
    ('igUnsignedShortMetaField', 1, 0),
    ('igIntMetaField', 1, 0),
    ('igUnsignedIntMetaField', 1, 0),
    ('igUnsignedLongMetaField', 1, 0),
    ('igEnumMetaField', 1, 0),
    ('igRawRefMetaField', 1, 0),
    ('igMemoryRefMetaField', 1, 0),
    ('igStringMetaField', 1, 0),
    ('igObjectRefMetaField', 1, 0),
    ('igIntArrayMetaField', 0, 0),
    ('igCharArrayMetaField', 0, 0),
    ('igUnsignedCharMetaField', 0, 0),
    ('igFloatMetaField', 0, 0),
    ('igLongMetaField', 0, 0),
    ('igStructMetaField', 0, 0),
    ('igMatrix44fMetaField', 0, 0),
    ('igUnsignedCharArrayMetaField', 0, 0),
    ('igVec4fMetaField', 0, 0),
    ('igDoubleMetaField', 0, 0),
    ('igVec3fMetaField', 0, 0),
    ('igUnsignedShortArrayMetaField', 0, 0),
    ('igUnsignedLongArrayMetaField', 0, 0),
    ('igUnsignedIntArrayMetaField', 0, 0),
    ('igStringArrayMetaField', 0, 0),
    ('igShortArrayMetaField', 0, 0),
    ('igRawRefArrayMetaField', 0, 0),
    ('igObjectRefArrayMetaField', 0, 0),
    ('igMemoryRefArrayMetaField', 0, 0),
    ('igLongArrayMetaField', 0, 0),
    ('igFloatArrayMetaField', 0, 0),
    ('igEnumArrayMetaField', 0, 0),
    ('igDoubleArrayMetaField', 0, 0),
    ('igDependencyMetaField', 0, 0),
    ('igBoolArrayMetaField', 0, 0),
    ('igMemoryDescriptorMetaField', 0, 0),
    ('igVertexBlendShaderCapsInfoMetaField', 0, 0),
    ('igTrackedElementMetaField', 0, 0),
    ('igVec4fArrayMetaField', 0, 0),
    ('igVec2fMetaField', 0, 0),
]

# (name, major, minor, parent_name, slot_count, [(field_short, slot, size)])
V4_META_OBJECTS = [
    # [0] (0103)
    ('igObject', 1, 0, None, 3,
     []),
    # [1] (0103)
    ('igNamedObject', 0, 0, 'igObject', 4,
     [('String', 3, 4)]),
    # [2] (0103)
    ('igDirEntry', 0, 0, 'igNamedObject', 8,
     [('String', 3, 4)]),
    # [3] (0103)
    ('igObjectDirEntry', 0, 0, 'igDirEntry', 13,
     [('String', 3, 4), ('Int', 12, 4)]),
    # [4] (0103)
    ('igMemoryDirEntry', 0, 0, 'igDirEntry', 14,
     [('String', 3, 4), ('Int', 8, 4), ('Int', 11, 4), ('Bool', 12, 1), ('Int', 13, 4)]),
    # [5] (0103)
    ('igExternalDirEntry', 0, 0, 'igDirEntry', 12,
     [('String', 3, 4), ('String', 8, 4), ('String', 9, 4), ('Int', 10, 4)]),
    # [6] (0103)
    ('igExternalImageEntry', 0, 0, 'igExternalDirEntry', 12,
     [('String', 3, 4), ('String', 8, 4), ('String', 9, 4), ('Int', 10, 4)]),
    # [7] (0103)
    ('igExternalIndexedEntry', 0, 0, 'igDirEntry', 14,
     [('String', 3, 4), ('Int', 8, 4), ('Int', 9, 4), ('Int', 11, 4), ('Int', 13, 4)]),
    # [8] (0103)
    ('igExternalInfoEntry', 0, 0, 'igDirEntry', 11,
     [('String', 3, 4), ('String', 8, 4), ('Int', 9, 4), ('String', 10, 4)]),
    # [9] (0103)
    ('igAttr', 0, 0, 'igObject', 4,
     [('Short', 3, 2)]),
    # [10] (0103)
    ('igVisualAttribute', 0, 0, 'igAttr', 4,
     [('Short', 3, 2)]),
    # [11] (0103)
    ('igTextureAttr', 0, 0, 'igVisualAttribute', 19,
     [('Short', 3, 2), ('UnsignedInt', 4, 4), ('Enum', 5, 4), ('Enum', 6, 4), ('Enum', 7, 4), ('Enum', 8, 4), ('Enum', 10, 4), ('Enum', 11, 4), ('ObjectRef', 12, 4), ('Bool', 13, 1), ('ObjectRef', 14, 4), ('Int', 15, 4), ('ObjectRef', 16, 4)]),
    # [12] (0103)
    ('igDataList', 0, 0, 'igObject', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [13] (0103)
    ('igObjectList', 0, 0, 'igDataList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [14] (0103)
    ('igImageMipMapList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [15] (0103)
    ('igClut', 0, 0, 'igObject', 10,
     [('Enum', 3, 4), ('UnsignedInt', 4, 4), ('Int', 5, 4), ('MemoryRef', 6, 4), ('Int', 7, 4)]),
    # [16] (0103)
    ('igTextureBindAttr', 0, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('ObjectRef', 4, 4), ('Int', 5, 4)]),
    # [17] (0103)
    ('igImage', 0, 0, 'igObject', 24,
     [('UnsignedInt', 3, 4), ('UnsignedInt', 4, 4), ('UnsignedInt', 5, 4), ('UnsignedInt', 6, 4), ('UnsignedInt', 7, 4), ('UnsignedInt', 8, 4), ('UnsignedInt', 9, 4), ('UnsignedInt', 10, 4), ('UnsignedInt', 11, 4), ('Enum', 12, 4), ('Int', 13, 4), ('MemoryRef', 14, 4), ('MemoryRef', 15, 4), ('Bool', 16, 1), ('UnsignedInt', 17, 4), ('ObjectRef', 18, 4), ('UnsignedInt', 19, 4), ('Int', 20, 4), ('Bool', 21, 1), ('UnsignedInt', 22, 4), ('String', 23, 4)]),
    # [18] (0103)
    ('igInfoList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [19] (0103)
    ('igAnimationTransitionDefinitionList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [20] (0103)
    ('igAnimationTrackList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [21] (0103)
    ('igAnimationBindingList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [22] (0103)
    ('igAnimation', 0, 0, 'igNamedObject', 12,
     [('String', 3, 4), ('Int', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('Long', 8, 8), ('Long', 9, 8), ('Long', 10, 8), ('ObjectRef', 11, 4)]),
    # [23] (0103)
    ('igSkin', 0, 0, 'igNamedObject', 6,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4)]),
    # [24] (0103)
    ('igVolume', 0, 0, 'igObject', 3,
     []),
    # [25] (0103)
    ('igAABox', 0, 0, 'igVolume', 5,
     [('Vec3f', 3, 12), ('Vec3f', 4, 12)]),
    # [26] (0103)
    ('igAttrList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [27] (0103)
    ('igNodeList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [28] (0103)
    ('igNode', 0, 0, 'igNamedObject', 7,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4)]),
    # [29] (0103)
    ('igGroup', 0, 0, 'igNode', 8,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4)]),
    # [30] (0103)
    ('igAttrSet', 0, 0, 'igGroup', 10,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1)]),
    # [31] (0103)
    ('igGeometry', 0, 0, 'igAttrSet', 11,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1)]),
    # [32] (0103)
    ('igSkeletonBoneInfo', 0, 0, 'igNamedObject', 7,
     [('String', 3, 4), ('Int', 4, 4), ('Int', 5, 4), ('Int', 6, 4)]),
    # [33] (0103)
    ('igSkeletonBoneInfoList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [34] (0103)
    ('igAnimationHierarchy', 0, 0, 'igNamedObject', 5,
     [('String', 3, 4), ('MemoryRef', 4, 4)]),
    # [35] (0103)
    ('igSkeleton', 0, 0, 'igAnimationHierarchy', 8,
     [('String', 3, 4), ('MemoryRef', 4, 4), ('ObjectRef', 5, 4), ('MemoryRef', 6, 4), ('Int', 7, 4)]),
    # [36] (0103)
    ('igAnimationTrack', 0, 0, 'igNamedObject', 6,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Vec4f', 5, 16)]),
    # [37] (0103)
    ('igAnimationBinding', 0, 0, 'igObject', 6,
     [('ObjectRef', 3, 4), ('MemoryRef', 4, 4), ('Int', 5, 4)]),
    # [38] (0103)
    ('igGeometryAttr', 0, 0, 'igVisualAttribute', 13,
     [('Short', 3, 2), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('Enum', 6, 4), ('UnsignedInt', 7, 4), ('UnsignedInt', 8, 4), ('ObjectRef', 9, 4), ('Int', 10, 4), ('ObjectRef', 11, 4), ('ObjectRef', 12, 4)]),
    # [39] (0103)
    ('igGeometryAttr1_5', 0, 0, 'igGeometryAttr', 14,
     [('Short', 3, 2), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('Enum', 6, 4), ('UnsignedInt', 7, 4), ('UnsignedInt', 8, 4), ('ObjectRef', 9, 4), ('Int', 10, 4), ('ObjectRef', 11, 4), ('ObjectRef', 12, 4), ('ObjectRef', 13, 4)]),
    # [40] (0103)
    ('igIndexArray', 0, 0, 'igObject', 8,
     [('MemoryRef', 3, 4), ('UnsignedInt', 4, 4), ('Enum', 5, 4), ('UnsignedInt', 6, 4)]),
    # [41] (0103)
    ('igVertexArray', 0, 0, 'igObject', 7,
     [('MemoryRef', 3, 4), ('UnsignedInt', 4, 4), ('UnsignedInt', 5, 4), ('UnsignedInt', 6, 4)]),
    # [42] (0103)
    ('igVertexArray1_1', 0, 0, 'igVertexArray', 13,
     [('MemoryRef', 3, 4), ('UnsignedInt', 4, 4), ('UnsignedInt', 5, 4), ('UnsignedInt', 6, 4), ('Struct', 7, 4), ('MemoryRef', 8, 4), ('MemoryRef', 9, 4), ('MemoryRef', 11, 4)]),
    # [43] (0103)
    ('igTextureStateAttr', 0, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('Bool', 4, 1), ('Int', 5, 4)]),
    # [44] (0103)
    ('igMaterialAttr', 0, 0, 'igVisualAttribute', 10,
     [('Short', 3, 2), ('Float', 4, 4), ('Vec4f', 5, 16), ('Vec4f', 6, 16), ('Vec4f', 7, 16), ('Vec4f', 8, 16), ('UnsignedInt', 9, 4)]),
    # [45] (0103)
    ('igColorAttr', 0, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('Vec4f', 4, 16)]),
    # [46] (0103)
    ('igLightingStateAttr', 0, 0, 'igVisualAttribute', 5,
     [('Short', 3, 2), ('Bool', 4, 1)]),
    # [47] (0103)
    ('igModelViewMatrixBoneSelect', 0, 0, 'igGroup', 9,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4), ('Int', 8, 4)]),
    # [48] (0103)
    ('igAnimationCombinerList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [49] (0103)
    ('igAppearanceList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [50] (0103)
    ('igSkinList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [51] (0103)
    ('igAnimationList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [52] (0103)
    ('igSkeletonList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [53] (0103)
    ('igInfo', 0, 0, 'igNamedObject', 6,
     [('String', 3, 4), ('Bool', 5, 1)]),
    # [54] (0103)
    ('igAnimationDatabase', 0, 0, 'igInfo', 11,
     [('String', 3, 4), ('Bool', 5, 1), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('ObjectRef', 9, 4), ('ObjectRef', 10, 4)]),
    # [55] (0103)
    ('igBlendMatrixSelect', 0, 0, 'igAttrSet', 13,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('Bool', 9, 1), ('ObjectRef', 10, 4), ('Matrix44f', 11, 64), ('Matrix44f', 12, 64)]),
    # [56] (0103)
    ('igIntList', 0, 0, 'igDataList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [57] (0103)
    ('igVertexBlendStateAttr', 0, 0, 'igVisualAttribute', 5,
     [('Short', 3, 2), ('Bool', 4, 1)]),
    # [58] (0103)
    ('igCullFaceAttr', 0, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('Bool', 4, 1), ('Enum', 5, 4)]),
    # [59] (0103)
    ('igSegment', 0, 0, 'igGroup', 8,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4)]),
    # [60] (v6-translated)
    ('igAlphaFunctionAttr', 1, 0, 'igVisualAttribute', 7,
     [('Short', 3, 2), ('Enum', 5, 4), ('Float', 6, 4)]),
    # [61] (v6-translated)
    ('igAlphaStateAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('Bool', 5, 1)]),
    # [62] (v6-translated)
    ('igBlendStateAttr', 1, 0, 'igVisualAttribute', 6,
     [('Short', 3, 2), ('Bool', 5, 1)]),
    # [63] (v6-translated)
    ('igBlendFunctionAttr', 1, 0, 'igVisualAttribute', 16,
     [('Short', 3, 2), ('Enum', 5, 4), ('Enum', 6, 4), ('Enum', 7, 4), ('ObjectRef', 8, 4), ('UnsignedChar', 9, 1), ('Short', 10, 2), ('Enum', 12, 4), ('Enum', 13, 4), ('Enum', 14, 4), ('Enum', 15, 4)]),
    # [64] (cable)
    ('igAnimationSystem', 0, 0, 'igNamedObject', 5,
     [('String', 3, 4), ('ObjectRef', 4, 4)]),
    # [65] (cable)
    ('igAnimationCombiner', 0, 0, 'igAnimationSystem', 15,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('MemoryRef', 8, 4), ('MemoryRef', 9, 4), ('Long', 10, 8), ('Bool', 11, 1), ('MemoryRef', 13, 4), ('MemoryRef', 14, 4)]),
    # [66] (cable)
    ('igAnimationCombinerBoneInfo', 0, 0, 'igObject', 9,
     [('ObjectRef', 3, 4), ('ObjectRef', 4, 4), ('Vec4f', 5, 16), ('Vec3f', 6, 12), ('Int', 7, 4), ('Bool', 8, 1)]),
    # [67] (cable)
    ('igAnimationCombinerBoneInfoList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [68] (cable)
    ('igAnimationCombinerBoneInfoListList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [69] (cable)
    ('igAnimationState', 0, 0, 'igObject', 21,
     [('ObjectRef', 3, 4), ('Enum', 4, 4), ('Enum', 5, 4), ('Enum', 6, 4), ('ObjectRef', 7, 4), ('Bool', 8, 1), ('Float', 9, 4), ('Long', 10, 8), ('Long', 11, 8), ('Float', 12, 4), ('Long', 13, 8), ('Long', 14, 8), ('Float', 15, 4), ('Float', 16, 4), ('Long', 17, 8), ('Long', 18, 8)]),
    # [70] (cable)
    ('igAnimationStateList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [71] (cable)
    ('igAnimationModifierList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [72] (cable)
    ('igActorInfo', 0, 0, 'igInfo', 11,
     [('String', 3, 4), ('Bool', 5, 1), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('ObjectRef', 9, 4), ('ObjectRef', 10, 4)]),
    # [73] (cable)
    ('igActorList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [74] (cable)
    ('igActor', 0, 0, 'igGroup', 19,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('Int', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4), ('MemoryRef', 9, 4), ('MemoryRef', 10, 4), ('ObjectRef', 11, 4), ('ObjectRef', 12, 4), ('ObjectRef', 13, 4), ('Matrix44f', 14, 64)]),
    # [75] (cable)
    ('igAppearance', 0, 0, 'igNamedObject', 9,
     [('String', 3, 4), ('ObjectRef', 4, 4), ('ObjectRef', 5, 4), ('ObjectRef', 6, 4), ('ObjectRef', 7, 4), ('ObjectRef', 8, 4)]),
    # [76] (cable)
    ('igStringObjList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
    # [77] (cable)
    ('igModelViewMatrixBoneSelectList', 0, 0, 'igObjectList', 6,
     [('Int', 3, 4), ('Int', 4, 4), ('MemoryRef', 5, 4)]),
]

N_BASE_METAS = 60
# base + blend/alpha render-state attrs (ANIM-mode slice)
N_ANIM_METAS = 64

V4_ALIGNMENT = bytes.fromhex('2e00000001000000020000000a00000010000000496d616765446174610056657274657841727261794461746100')
