"""Generate objective data for XML2/MUA game engine.

XML2 objectives are a two-part system:
  1. **Mission ENGB** — defines objective metadata (name, description, XP, type)
     in ``data/missions/`` as compiled XMLB.
  2. **Zone script** — controls objective state at runtime via::

         objective("obj_id", "EOBJCMD_SHOW")       # reveal to player
         objective("obj_id", "EOBJCMD_COMPLETE")    # mark done
         objective("obj_id", "EOBJCMD_INCREMENT")   # +1 counter
         getObjective("obj_id", "COMPLETE")          # query (returns 0/1)
         getObjective("obj_id", "COUNT")             # query counter value

This module generates BOTH the mission ENGB text (Raven XML format) and
the zone-script Python code.
"""

import bpy


# ── Step-type → objective type mapping ──────────────────────────────────
# XML2 objective types: "normal", "object", "person"
_STEP_TYPE_MAP = {
    'GO_TO':      'normal',
    'DESTROY':    'normal',
    'COLLECT':    'object',
    'INTERACT':   'object',
    'DEFEAT_ALL': 'person',
    'CUSTOM':     'normal',
}


def _escape(text):
    """Escape quotes for embedding in Raven XMLB text attributes."""
    return text.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')


# =========================================================================
# Mission ENGB generation (objective definitions)
# =========================================================================

def generate_mission_engb_text(scene):
    """Generate a mission ENGB file in Raven text format.

    Returns a string, or empty string if no objectives exist.
    The file defines all objectives so the game engine knows about them.
    """
    objectives = scene.mm_objectives
    if len(objectives) == 0:
        return ""

    settings = scene.mm_settings
    map_name = settings.map_name
    act_number = settings.act

    from .xml_gen import _RavenWriter

    w = _RavenWriter("MISSION")
    w.attr("act", str(act_number))

    for obj in objectives:
        attrs = {}
        attrs['name'] = obj.obj_name
        attrs['descname'] = obj.display_text
        attrs['enabled'] = 'true' if obj.auto_activate else 'false'
        attrs['major'] = 'true'  # top-level objectives are major
        attrs['type'] = 'normal'
        attrs['xp'] = '0'

        # If the objective has a description from first step, use it
        if len(obj.steps) > 0 and obj.steps[0].description:
            attrs['description'] = obj.steps[0].description

        # Zone reference
        attrs['zone'] = map_name

        w.blank()
        w.element("OBJECTIVE", attrs)

        # Sub-objectives for each step (if multiple steps)
        if len(obj.steps) > 1:
            for si, step in enumerate(obj.steps):
                sub_attrs = {}
                sub_attrs['name'] = f"{obj.obj_name}_{chr(97 + si)}"  # a, b, c...
                sub_attrs['descname'] = step.description or f"Step {si + 1}"
                sub_attrs['enabled'] = 'false'
                sub_attrs['major'] = 'false'
                sub_attrs['parentname'] = obj.obj_name
                sub_attrs['type'] = _STEP_TYPE_MAP.get(step.step_type, 'normal')
                sub_attrs['xp'] = '0'
                sub_attrs['zone'] = map_name

                if step.step_type == 'COLLECT' and step.count > 1:
                    sub_attrs['count'] = str(step.count)
                    if not step.description:
                        sub_attrs['description'] = '%d of %d collected'

                w.blank()
                w.element("OBJECTIVE", sub_attrs)

    return w.build()


# =========================================================================
# Zone script generation (objective runtime control)
# =========================================================================

def generate_objective_script(scene):
    """Generate zone-script Python code for objective control.

    Uses the real XML2 API:
        objective("id", "EOBJCMD_SHOW")
        objective("id", "EOBJCMD_COMPLETE")
        objective("id", "EOBJCMD_INCREMENT")
        getObjective("id", "COMPLETE")   -> 0 or 1
        getObjective("id", "COUNT")      -> int

    Returns a string of Python code, or empty string if no objectives.
    """
    objectives = scene.mm_objectives
    if len(objectives) == 0:
        return ""

    lines = []
    lines.append("")
    lines.append("# ==============================================")
    lines.append("# Objectives — auto-generated by Map Maker Tools")
    lines.append("# ==============================================")
    lines.append("")

    # --- OnPostInit: show auto-activated objectives ---
    lines.append("def _init_objectives():")
    lines.append('    """Show initial objectives on zone load."""')

    auto_activate = [o for o in objectives if o.auto_activate]
    if auto_activate:
        for obj in auto_activate:
            lines.append(f'    objective("{obj.obj_name}", "EOBJCMD_SHOW")')
            # Also show sub-objectives if multi-step
            if len(obj.steps) > 1:
                for si in range(len(obj.steps)):
                    sub_id = f"{obj.obj_name}_{chr(97 + si)}"
                    lines.append(f'    objective("{sub_id}", "EOBJCMD_SHOW")')
    else:
        lines.append("    pass")

    lines.append("")
    lines.append("")

    # --- Helper: complete an objective and chain to next ---
    lines.append("def _complete_objective(name):")
    lines.append('    """Mark objective complete and activate next in chain."""')
    lines.append(f'    objective(name, "EOBJCMD_COMPLETE")')

    # Build chain map
    chains = {}
    for obj in objectives:
        if obj.next_objective:
            chains[obj.obj_name] = obj.next_objective

    if chains:
        lines.append("    # Objective chaining")
        first = True
        for src, dst in chains.items():
            prefix = "if" if first else "elif"
            lines.append(f'    {prefix} name == "{src}":')
            lines.append(f'        objective("{dst}", "EOBJCMD_SHOW")')
            first = False
    lines.append("")
    lines.append("")

    # --- Per-objective completion helpers ---
    for obj in objectives:
        lines.append(f"# --- {obj.display_text} ---")

        if len(obj.steps) == 1:
            step = obj.steps[0]
            if step.step_type == 'COLLECT' and step.count > 1:
                # Counter-based objective
                lines.append(f"def _on_{obj.obj_name}_progress():")
                lines.append(f'    """Call each time an item is collected."""')
                lines.append(f'    objective("{obj.obj_name}", "EOBJCMD_INCREMENT")')
                lines.append(f'    count = getObjective("{obj.obj_name}", "COUNT")')
                lines.append(f"    if count >= {step.count}:")
                lines.append(f'        _complete_objective("{obj.obj_name}")')
                if step.completion_script:
                    lines.append(f"        {step.completion_script}")
                lines.append("")
            else:
                # Simple completion
                lines.append(f"def _on_{obj.obj_name}_complete():")
                lines.append(f'    """Call when objective is done."""')
                lines.append(f'    _complete_objective("{obj.obj_name}")')
                if step.completion_script:
                    lines.append(f"    {step.completion_script}")
                lines.append("")

        elif len(obj.steps) > 1:
            # Multi-step: each sub-objective has its own completion
            for si, step in enumerate(obj.steps):
                sub_id = f"{obj.obj_name}_{chr(97 + si)}"

                if step.step_type == 'COLLECT' and step.count > 1:
                    lines.append(f"def _on_{sub_id}_progress():")
                    lines.append(f'    """Call each time an item is collected for step {si+1}."""')
                    lines.append(f'    objective("{sub_id}", "EOBJCMD_INCREMENT")')
                    lines.append(f'    count = getObjective("{sub_id}", "COUNT")')
                    lines.append(f"    if count >= {step.count}:")
                    lines.append(f'        objective("{sub_id}", "EOBJCMD_COMPLETE")')
                    lines.append(f"        _check_{obj.obj_name}_all()")
                    if step.completion_script:
                        lines.append(f"        {step.completion_script}")
                    lines.append("")
                else:
                    lines.append(f"def _on_{sub_id}_complete():")
                    lines.append(f'    """Call when step {si+1} is done."""')
                    lines.append(f'    objective("{sub_id}", "EOBJCMD_COMPLETE")')
                    lines.append(f"    _check_{obj.obj_name}_all()")
                    if step.completion_script:
                        lines.append(f"    {step.completion_script}")
                    lines.append("")

            # Check-all function for parent objective
            lines.append(f"def _check_{obj.obj_name}_all():")
            lines.append(f'    """Complete parent when all sub-objectives done."""')
            conditions = []
            for si in range(len(obj.steps)):
                sub_id = f"{obj.obj_name}_{chr(97 + si)}"
                conditions.append(f'getObjective("{sub_id}", "COMPLETE") == 1')
            lines.append(f"    if {' and '.join(conditions)}:")
            lines.append(f'        _complete_objective("{obj.obj_name}")')
            lines.append("")

        else:
            # No steps — just a marker objective
            lines.append(f"def _on_{obj.obj_name}_complete():")
            lines.append(f'    _complete_objective("{obj.obj_name}")')
            lines.append("")

        lines.append("")

    return "\n".join(lines)


def generate_zone_script_with_objectives(scene):
    """Generate a complete zone script with objectives.

    Returns the full Python script as a string, or empty string if no
    objectives are defined (so the build pipeline can skip writing).
    """
    objectives = scene.mm_objectives
    if len(objectives) == 0:
        return ""  # No objectives = don't overwrite existing zone script

    settings = scene.mm_settings
    map_name = settings.map_name

    lines = []
    lines.append(f"# Zone script for {map_name}")
    lines.append("# Auto-generated by Map Maker Tools")
    lines.append("")

    obj_code = generate_objective_script(scene)
    lines.append(obj_code)
    lines.append("")
    lines.append("def OnPostInit():")
    lines.append("    _init_objectives()")
    lines.append("")
    lines.append("def OnActComplete():")
    lines.append("    pass")
    lines.append("")

    return "\n".join(lines)
